== ri-analytics-classification-twitter image:https://img.shields.io/badge/License-EPL%202.0-blue.svg["EPL 2.0", link="https://www.eclipse.org/legal/epl-2.0/"]

This service was created as a result of the OpenReq project funded by the European Union Horizon 2020 Research and Innovation programme under grant agreement No 732463.

== Technical description
=== What does the microservice do
The ri-analytics-classification-twitter microservice is cabable of classifying English and Italien tweets into __problem report__, __inquiry__, and __irrelevant__. 

=== Which technologies are used
- Docker (-> https://www.docker.com/)
- SentiStrength (-> http://sentistrength.wlv.ac.uk/)


=== How to install it
*ri-analytics-classification-twitter* requires you to: 

. aquire the sentistrength library from http://sentistrength.wlv.ac.uk/ 

. mount the SentiStrength.jar file in the Docker run environment (e.g., `docker run --rm -d -v "<path>/SentiStrength.jar:/app/amazon-kinesis-client-python/sentistrength/SentiStrength.jar"`)

. set a Docker ARG __GDRIVE_DL_LINK__ to the <DL_LINK_ID> (e.g, `docker build --build-arg "GDRIVE_DL_LINK=1fcMjYmmjY9-WMOauYle6fFLooJ0u9OlU"`). This will download and unzip the classification models from Google Drive.

.. the link should contain a models.zip archive. Inside it needs a folder per language models/english and models/italian.

.. in the subfolders (for each language) place all models as specified in the config/ files

.. the code runs the feature extraction exactly in the order as specified in the config files

Run the following commands to start the microservice:

. `docker build --rm -f "Dockerfile" --build-arg "GDRIVE_DL_LINK=<DL_LINK_ID>" -t ri-analytics-classification-twitter:latest .`

. `docker run --rm -d -v "<path>/SentiStrength.jar:/app/amazon-kinesis-client-python/sentistrength/SentiStrength.jar" -p 9655:9655 ri-analytics-classification-twitter`


A full description of the the microservice can be found in the following swagger documentation:

=== How to use it (high-level description)
The API is documented by using Swagger2:

- link:http://217.172.12.199/registry/#/services/ri-analytics-classification-twitter[Rendered Documentation]

=== Notes for developers 
None.

=== Sources
None.

== How to contribute
See OpenReq project contribution link:https://github.com/OpenReqEU/OpenReq/blob/master/CONTRIBUTING.md[Guidlines]

== License
Free use of this software is granted under the terms of the EPL version 2 (EPL2.0).
